//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECoupoun.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class APIDetail
    {
        public int APIId { get; set; }
        public int CategoryId { get; set; }
        public int ProviderId { get; set; }
        public string ProviderCatName { get; set; }
        public string ServiceUrl { get; set; }
        public string APIKey { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsActive { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
