//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECoupoun.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Category
    {
        public Category()
        {
            this.APIDetails = new HashSet<APIDetail>();
            this.Categories1 = new HashSet<Category>();
            this.CategoryProviderMappings = new HashSet<CategoryProviderMapping>();
            this.ProductMasters = new HashSet<ProductMaster>();
        }
    
        public int CategoryId { get; set; }
        public Nullable<int> CategoryParentId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsActive { get; set; }
        public string MappingName { get; set; }
        public string Image { get; set; }
    
        public virtual ICollection<APIDetail> APIDetails { get; set; }
        public virtual ICollection<Category> Categories1 { get; set; }
        public virtual Category Category1 { get; set; }
        public virtual ICollection<CategoryProviderMapping> CategoryProviderMappings { get; set; }
        public virtual ICollection<ProductMaster> ProductMasters { get; set; }
    }
}
