//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECoupoun.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductLink
    {
        public int ProductId { get; set; }
        public int ProviderId { get; set; }
        public string SoruceUrl { get; set; }
        public string MobileUrl { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public bool IsActive { get; set; }
    
        public virtual ProductMaster ProductMaster { get; set; }
        public virtual Provider Provider { get; set; }
        public virtual ProductMaster ProductMaster1 { get; set; }
        public virtual Provider Provider1 { get; set; }
    }
}
