//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECoupoun.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductMaster
    {
        public ProductMaster()
        {
            this.ProductLinks = new HashSet<ProductLink>();
            this.ProductLinks1 = new HashSet<ProductLink>();
            this.ProductPricings = new HashSet<ProductPricing>();
            this.ProductPricings1 = new HashSet<ProductPricing>();
        }
    
        public int ProductId { get; set; }
        public int CategoryId { get; set; }
        public Nullable<int> ManufacturerId { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public string Name { get; set; }
        public string LongDescription { get; set; }
        public string ModelNumber { get; set; }
        public string Image { get; set; }
        public string Color { get; set; }
        public Nullable<double> Size { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual ICollection<ProductLink> ProductLinks { get; set; }
        public virtual ICollection<ProductLink> ProductLinks1 { get; set; }
        public virtual ICollection<ProductPricing> ProductPricings { get; set; }
        public virtual ICollection<ProductPricing> ProductPricings1 { get; set; }
    }
}
