//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECoupoun.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductPricing
    {
        public int ProductId { get; set; }
        public int ProviderId { get; set; }
        public int SKU { get; set; }
        public decimal RegularPrice { get; set; }
        public decimal SalePrice { get; set; }
        public System.DateTime AsofDate { get; set; }
    
        public virtual ProductMaster ProductMaster { get; set; }
        public virtual Provider Provider { get; set; }
    }
}
